# -*- coding: utf-8 -*-
"""adjencyfinder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sX_c_U2P41H4xbYiWJiRJ06i_brq8xx3
"""

import geopandas as gpd

shp = gpd.read_file("ks_vest_20.shp")
shp = shp.set_index("NAMELSAD")
shp = shp.sort_index()
shp.head()

import pandas as pd
adj = pd.DataFrame(shp.index).set_index("NAMELSAD")
#adj = gpd.GeoDataFrame(shp.index).set_index("NAMELSAD")
adj

adj.index = adj.index + " " + adj.groupby(level=0).cumcount().astype(str).replace("0","")
shp.index = shp.index + " " +  shp.groupby(level=0).cumcount().astype(str).replace("0","")

sum(adj.index.duplicated())

sum(shp.index.duplicated())

buffered = shp.to_crs(3857).buffer(50).buffer(-50)
conv = shp.to_crs(3857)

import warnings
import shp

with warnings.catch_warnings(record=True):
    for place in shp.index:
        print(place)
        borders = (buffered.intersects(conv.loc[place, "geometry"])*1) 
        adj[place] = borders
adj.show()

with warnings.catch_warnings(record=True):
    adj['geometry'] = shp['geometry']
    adj=adj.copy()
adj

import random
i = adj.index[random.randrange(0, 4000)]
print(i)
plotter = gpd.GeoDataFrame([adj.index, adj[i], adj['geometry']])
plotter = plotter.transpose()
plotter.columns = ["name", "place", "geometry"]
plotter = gpd.GeoDataFrame(plotter)
plotter.explore("place", cmap='bwr')

adjfinal = adj[adj.columns[0:-1]]
adjfinal

adjfinal.to_csv("kansas_adjency.csv")